from datetime import datetime
from decimal import Decimal
from sqlalchemy import Boolean, DateTime, ForeignKey, Index, Numeric, String, Text, UniqueConstraint
from sqlalchemy.orm import Mapped, mapped_column
from app.db.base import Base, utc_now

class User(Base):
    __tablename__ = "users"
    id: Mapped[int] = mapped_column(primary_key=True); telegram_id: Mapped[int] = mapped_column(unique=True, index=True); username: Mapped[str | None] = mapped_column(String(255)); first_name: Mapped[str | None] = mapped_column(String(255)); last_name: Mapped[str | None] = mapped_column(String(255)); created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=utc_now); last_login_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=utc_now); is_active: Mapped[bool] = mapped_column(Boolean, default=True)
class WatchlistItem(Base):
    __tablename__ = "watchlist_items"; id: Mapped[int] = mapped_column(primary_key=True); user_id: Mapped[int] = mapped_column(ForeignKey("users.id", ondelete="CASCADE"), index=True); gift_id: Mapped[int] = mapped_column(ForeignKey("gifts.id", ondelete="CASCADE"), index=True); created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=utc_now); __table_args__ = (UniqueConstraint("user_id", "gift_id", name="uq_watchlist_user_gift"),)
class PortfolioWallet(Base):
    __tablename__ = "portfolio_wallets"; id: Mapped[int] = mapped_column(primary_key=True); user_id: Mapped[int] = mapped_column(ForeignKey("users.id", ondelete="CASCADE"), index=True); address: Mapped[str] = mapped_column(String(128)); label: Mapped[str | None] = mapped_column(String(255)); created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=utc_now); __table_args__ = (UniqueConstraint("user_id", "address", name="uq_portfolio_user_address"),)
class AlertRule(Base):
    __tablename__ = "alert_rules"; id: Mapped[int] = mapped_column(primary_key=True); user_id: Mapped[int] = mapped_column(ForeignKey("users.id", ondelete="CASCADE"), index=True); gift_id: Mapped[int | None] = mapped_column(ForeignKey("gifts.id", ondelete="CASCADE"), index=True); rule_type: Mapped[str] = mapped_column(String(32)); threshold: Mapped[Decimal] = mapped_column(Numeric(24, 9)); is_active: Mapped[bool] = mapped_column(Boolean, default=True); created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=utc_now)
class AlertEvent(Base):
    __tablename__ = "alert_events"; id: Mapped[int] = mapped_column(primary_key=True); rule_id: Mapped[int] = mapped_column(ForeignKey("alert_rules.id", ondelete="CASCADE"), index=True); user_id: Mapped[int] = mapped_column(ForeignKey("users.id", ondelete="CASCADE"), index=True); gift_id: Mapped[int | None] = mapped_column(ForeignKey("gifts.id", ondelete="CASCADE"), index=True); message: Mapped[str] = mapped_column(Text); observed_value: Mapped[Decimal | None] = mapped_column(Numeric(24, 9)); is_read: Mapped[bool] = mapped_column(Boolean, default=False); created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=utc_now); notification_sent_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True)); notification_attempts: Mapped[int] = mapped_column(default=0); notification_error: Mapped[str | None] = mapped_column(Text); __table_args__ = (Index("ix_alert_events_user_created", "user_id", "created_at"), Index("ix_alert_events_delivery", "notification_sent_at", "notification_attempts"))
