import { FormEvent, useEffect, useState } from "react";
import { Wallet, Plus, ShieldCheck, Trash2, LoaderCircle, RefreshCw } from "lucide-react";
import { addWallet, getPortfolioOverview, getWallets, removeWallet } from "../api";
import { EmptyState } from "../components/State";

type WalletItem = { id: number; address: string; label?: string | null };
type Overview = Awaited<ReturnType<typeof getPortfolioOverview>>;

export function Portfolio() {
  const [wallets, setWallets] = useState<WalletItem[]>([]); const [overview, setOverview] = useState<Overview | null>(null); const [address, setAddress] = useState(""); const [label, setLabel] = useState(""); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null);
  const load = async () => { setLoading(true); try { const [walletData, portfolio] = await Promise.all([getWallets(), getPortfolioOverview()]); setWallets(walletData.items); setOverview(portfolio); setError(null); } catch (e) { setError(e instanceof Error ? e.message : "Sign in to load portfolio"); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  const submit = async (event: FormEvent) => { event.preventDefault(); if (!address.trim()) return; setSaving(true); try { const created = await addWallet(address.trim(), label.trim() || undefined) as WalletItem; setWallets(items => items.some(item => item.id === created.id) ? items : [created, ...items]); setAddress(""); setLabel(""); await load(); } catch (e) { setError(e instanceof Error ? e.message : "Could not connect wallet"); } finally { setSaving(false); } };
  const remove = async (id: number) => { try { await removeWallet(id); setWallets(items => items.filter(item => item.id !== id)); await load(); } catch (e) { setError(e instanceof Error ? e.message : "Could not remove wallet"); } };
  const assetCount = overview?.total_assets ?? 0; const nftValue = Number(overview?.estimated_nft_value_ton ?? 0); const tonBalance = overview?.wallets.reduce((sum, wallet) => sum + Number(wallet.ton_balance), 0) ?? 0; const totalValue = nftValue + tonBalance;
  return <section className="page-section"><div className="section-head"><div><p className="eyebrow">CAPITAL VIEW</p><h2>Portfolio</h2></div><div className="top-actions"><span className="fresh">{wallets.length} connected wallet{wallets.length === 1 ? "" : "s"}</span><button className="icon-btn" aria-label="Refresh portfolio valuation" onClick={() => void load()} disabled={loading}><RefreshCw size={16} className={loading ? "spin" : ""}/></button></div></div><div className="portfolio-hero"><div><span className="kicker"><ShieldCheck size={15}/> Live TONAPI holdings</span><h3>Track what you own,<br/><em>with a market basis.</em></h3><p>NFT values use the latest verified market floor. Unknown assets stay unvalued.</p></div><div className="portfolio-total"><small>Total estimated value</small><strong>{loading ? "--" : `${totalValue.toFixed(3)} TON`}</strong><span>TON balance + valued NFTs</span></div></div>{error && <div className="notice error">{error}</div>}<form className="wallet-form" onSubmit={submit}><label>TON wallet address<input value={address} onChange={e => setAddress(e.target.value)} placeholder="EQ... or UQ..." minLength={10} required /></label><label>Label<input value={label} onChange={e => setLabel(e.target.value)} placeholder="Main wallet" /></label><button className="outline-btn" disabled={saving}>{saving ? <LoaderCircle className="spin" size={15}/> : <Plus size={15}/>} Connect wallet</button></form>{loading ? <div className="page-state"><LoaderCircle className="spin" size={22}/><span>Reading TONAPI holdings...</span></div> : wallets.length ? <div className="wallet-list">{wallets.map(item => <div className="wallet-row" key={item.id}><div><strong>{item.label || "Unnamed wallet"}</strong><small>{item.address}</small></div><button type="button" className="icon-btn" aria-label={`Remove ${item.label || "wallet"}`} onClick={() => void remove(item.id)}><Trash2 size={15}/></button></div>)}</div> : <EmptyState title="No wallets connected" detail="Connect a TON address to start building the portfolio view."/>}<div className="metric-grid portfolio-metrics"><div className="metric green"><span>Total estimated value</span><strong>{loading ? "--" : `${totalValue.toFixed(3)} TON`}</strong><small>Wallet balance plus valued NFTs</small></div><div className="metric blue"><span>Estimated NFT value</span><strong>{loading ? "--" : `${nftValue.toFixed(3)} TON`}</strong><small>Latest verified floors only</small></div><div className="metric violet"><span>TON balance</span><strong>{loading ? "--" : `${tonBalance.toFixed(3)} TON`}</strong><small>{assetCount} indexed NFT assets</small></div></div></section>;
}
